project:
  type: website

website:
  title: "Quarto Reprex"
  repo-url: https://github.com/isaactpetersen/QuartoReprex
  repo-actions: [edit, source, issue]

format:
  html:
    toc: true
    toc-depth: 5
    toc-title: Contents
    toc-location: right
    execute:
      error: true
      warning: true
    number-sections: true
    code-fold: show
    df-print: paged
    code-tools:
      source: true
      toggle: true
    link-external-newwindow: true
